#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

rm ~/.bashrc
ln -s $DIR/.bashrc ~/.bashrc
curl https://raw.githubusercontent.com/tpope/vim-sensible/master/plugin/sensible.vim > ~/.vimrc

if command -v apt-get >/dev/null; then
  command -v vim >/dev/null || (apt-get update && apt-get install -y vim)
else
  echo "Don't know how to install on this platform."
  exit 1
fi
